const data = {
    id: 0,
    from: '',
    to: '',
    image: '',
    "queryCost": 1,
    "latitude": 51.5064,
    "longitude": -0.12721,
    "resolvedAddress": "London, England, United Kingdom",
    "address": "london",
    "timezone": "Europe/London",
    "tzoffset": 0,
    "description": "Similar temperatures continuing with a chance of rain multiple days.",
    "days": [
     {
      "datetime": "2024-02-20",
      "datetimeEpoch": 1708387200,
      "tempmax": 12.2,
      "tempmin": 6.4,
      "temp": 9,
      "feelslikemax": 12.2,
      "feelslikemin": 4,
      "feelslike": 7.4,
      "dew": 6.5,
      "humidity": 84.3,
      "precip": 0,
      "precipprob": 48.4,
      "precipcover": 0,
      "preciptype": [
       "rain"
      ],
      "snow": 0,
      "snowdepth": 0,
      "windgust": 55.1,
      "windspeed": 27.7,
      "winddir": 226.8,
      "pressure": 1026.1,
      "cloudcover": 89.7,
      "visibility": 12.2,
      "solarradiation": 45.4,
      "solarenergy": 4.1,
      "uvindex": 2,
      "severerisk": 10,
      "sunrise": "07:05:42",
      "sunriseEpoch": 1708412742,
      "sunset": "17:23:47",
      "sunsetEpoch": 1708449827,
      "moonphase": 0.36,
      "conditions": "Rain, Partially cloudy",
      "description": "Partly cloudy throughout the day with a chance of rain.",
      "icon": "rain",
      "stations": [
       "EGWU",
       "EGLL",
       "D4121",
       "EGLC"
      ],
      "source": "comb",
      "hours": [
       {
        "datetime": "12:00:00",
        "datetimeEpoch": 1708430400,
        "temp": 10.2,
        "feelslike": 10.2,
        "humidity": 86.15,
        "dew": 8,
        "precip": 0,
        "precipprob": 0,
        "snow": 0,
        "snowdepth": 0,
        "preciptype": null,
        "windgust": 40.7,
        "windspeed": 17.3,
        "winddir": 216,
        "pressure": 1025.8,
        "visibility": 10,
        "cloudcover": 97.5,
        "solarradiation": 98,
        "solarenergy": 0.4,
        "uvindex": 1,
        "severerisk": 10,
        "conditions": "Overcast",
        "icon": "cloudy",
        "stations": [
         "EGWU",
         "EGLL",
         "D4121",
         "EGLC"
        ],
        "source": "obs"
       },
       {
        "datetime": "13:00:00",
        "datetimeEpoch": 1708434000,
        "temp": 11.1,
        "feelslike": 11.1,
        "humidity": 82.95,
        "dew": 8.3,
        "precip": 0,
        "precipprob": 0,
        "snow": 0,
        "snowdepth": 0,
        "preciptype": null,
        "windgust": 47.5,
        "windspeed": 21.1,
        "winddir": 232,
        "pressure": 1025,
        "visibility": 10,
        "cloudcover": 97.5,
        "solarradiation": 130,
        "solarenergy": 0.5,
        "uvindex": 1,
        "severerisk": 10,
        "conditions": "Overcast",
        "icon": "cloudy",
        "stations": [
         "EGWU",
         "EGLL",
         "D4121",
         "EGLC"
        ],
        "source": "obs"
       }
      ]
     }
    ],
    "alerts": [],
    "stations": {
     "EGWU": {
      "distance": 20850,
      "latitude": 51.55,
      "longitude": -0.42,
      "useCount": 0,
      "id": "EGWU",
      "name": "EGWU",
      "quality": 50,
      "contribution": 0
     },
     "EGLC": {
      "distance": 12300,
      "latitude": 51.5,
      "longitude": 0.05,
      "useCount": 0,
      "id": "EGLC",
      "name": "EGLC",
      "quality": 50,
      "contribution": 0
     },
     "EGLL": {
      "distance": 22564,
      "latitude": 51.48,
      "longitude": -0.45,
      "useCount": 0,
      "id": "EGLL",
      "name": "EGLL",
      "quality": 50,
      "contribution": 0
     },
     "D4121": {
      "distance": 17556,
      "latitude": 51.463,
      "longitude": -0.371,
      "useCount": 0,
      "id": "D4121",
      "name": "DW4121 London Heathow UK",
      "quality": 0,
      "contribution": 0
     },
     "F8628": {
      "distance": 14897,
      "latitude": 51.612,
      "longitude": 0.005,
      "useCount": 0,
      "id": "F8628",
      "name": "M0BPQ Chingford UK",
      "quality": 0,
      "contribution": 0
     }
    },
    "currentConditions": {
     "datetime": "17:30:00",
     "datetimeEpoch": 1708450200,
     "temp": 10.9,
     "feelslike": 10.9,
     "humidity": 75.7,
     "dew": 6.8,
     "precip": 0,
     "precipprob": 0,
     "snow": 0,
     "snowdepth": 0,
     "preciptype": null,
     "windgust": 17.6,
     "windspeed": 13.2,
     "winddir": 293,
     "pressure": 1023,
     "visibility": 10,
     "cloudcover": 100,
     "solarradiation": 0,
     "solarenergy": 0,
     "uvindex": 0,
     "conditions": "Overcast",
     "icon": "cloudy",
     "stations": [
      "D4121",
      "EGLC",
      "F8628"
     ],
     "source": "obs",
     "sunrise": "07:05:42",
     "sunriseEpoch": 1708412742,
     "sunset": "17:23:47",
     "sunsetEpoch": 1708449827,
     "moonphase": 0.36
    }
   }

   type myDataType = typeof data

   export default myDataType